### ISSUE TITLE
var_export does not handle circular references 

### ISSUE THREAD

**Issue by prathna124** [henzeb/var-export-wrapper#1]
We have installed this package and used it like below:-

In vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php in:-
use function Henzeb\VarExportWrapper\Support\Functions\var_export;

$configPath, '<?php return '.var_export($config).';'.PHP_EOL

faced below error:-

Exception

Serialization of 'Closure' is not allowed

at vendor/henzeb/var-export-wrapper/src/VarExportable.php:35
31▕ return;
32▕ }
33▕
34▕ $this->object = serialize(
➜ 35▕ $var
36▕ );
37▕ }
38▕
39▕ public static function __set_state(array $state)

  +3 vendor frames 
4 [internal]:0
Henzeb\VarExportWrapper\Support\Functions{closure}()

  +16 vendor frames 
21 artisan:37
Illuminate\Foundation\Console\Kernel::handle()

Please guide me on how to solve this.

**Comment by henzeb** [comment]
Not sure what you mean. All you have to do is install it and run `artisan config:cache`. You do not need to modify anything.

**Comment by prathna124** [comment]
If we do not use this (use function Henzeb\VarExportWrapper\Support\Functions\var_export; ) on file and do not modify anything and run artisan config:cache faced below error :-

var_export does not handle circular references

  at vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php:63
     59▕ 
     60▕         $configPath = $this->laravel->getCachedConfigPath();
     61▕ 
     62▕         $this->files->put(
  ➜  63▕             $configPath, '<?php return '.var_export($config, true).';'.PHP_EOL
     64▕         );
     65▕ 
     66▕         try {
     67▕             require $configPath;

      +14 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
      
      
    After Faced this error we have import (use function Henzeb\VarExportWrapper\Support\Functions\var_export; ) this on file and run config:cache faced below error :-
      
      
      Exception 

  Serialization of 'Closure' is not allowed

  at vendor/henzeb/var-export-wrapper/src/VarExportable.php:35
     31▕             return;
     32▕         }
     33▕ 
     34▕         $this->object = serialize(
  ➜  35▕             $var
     36▕         );
     37▕     }
     38▕ 
     39▕     public static function __set_state(array $state)

      +3 vendor frames 
  4   [internal]:0
      Henzeb\VarExportWrapper\Support\Functions\{closure}()

      +16 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
      
      
      Please guide me how to solve this error.

**Comment by henzeb** [comment]
I am sorry for the delay, I got sick and then extremely busy. Did you ever solve the issue?

If not, the only way I can reproduce it when I am using an object instance that has a closure set in a class property. and a _set_state implementation. If I run the command twice, first I get the full error stack, then a short error message. I never get the circular references message though. 

It may help if I have information about your php and laravel version.

**Comment by henzeb** [comment]
I am going to close this, as it is not reproducible.
